Don't Build WEAK_LINK_FORCE_IMPORT
Currently causes build failure:
error: a parameter list without types is only allowed in a function definition
WEAK_LINK_FORCE_IMPORT(CreateTextEncoding)